appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: Mw8gJ8Jybdg+JTet+d+Gt6U5rU0M+2Eo0ODgPzC3c46n1U1K5S/rNbMfsqYoG5t3eABjoXJf+1Om/MTO7EBlj4uLx9YGJ6t0pZdEMr544P+nNTT7DZU9h+XvwNfmFyR9nwO/Y7qRFJ3rGuZqy5D0Jd7VuAiS02dmB84aibsUxskGMI0ZtR4tKqmPbpGhs64WHz1ZetrqAnFPZ+ttYAU/t5c4XUtEypJyvx82tap9SklT71UsEoh/qQyV56rG8U0JWAcyMu5G9tzYvj6VUEPoUKfG210GW/3knmeXPTlDtBxQIdlfcNpwcNgU9xoplTnpx8Y2o9jaJfMFHG1FhvuqqDmvl0dtMDr0FU/o7ivf66tHuHCcHq9Xt0rG80BmlZpwDMjqjLYndRX+SE+HU12HzMRnPA5HliCkw5R73/Y/o3L+/dH1AzokfvQck5A/LDzBxp5mGo152zlkMQgSa4egWzvEj2xoeEapt0zcF5Dwgk0ncuKVkBh9EBhogd4BisHAYygXymos372eDBH356XroHo9MsLe44usGJKvj7Ekq1GjUDWwgTVNlGqLD+Ga1II8pR7GfLEYJCbePJV6KI0BGaIUeLpJKMLOrNcYgG0AGBj/Q//sIwnUapaQGgrigm86CODUNkctKUlNhe6B9hug8oqhNMFxiBwAkF1rG2Ia/7Y=}
conda_forge_output_validation: true
